Altered initial deploy handling.

diff --git a/rails/shell/functions b/rails/shell/functions
--- a/rails/shell/functions
+++ b/rails/shell/functions
@@ -318,11 +318,16 @@ rails_setup()
 
   configure_rvm
 
-  ( modules deploy ; deploy )
+  setup_application_server
+
+  module_or_error deploy "Deploy extension is missing (ext/deploy)"
+
+  if ! ( deploy )
+  then
+    warn "Deploy failed, after setup is complete inspect things and then retry via:\n sm deploy"
+  fi
 
   bootstrap_gems
-
-  setup_application_server
 }
 
 rails_server()
