Rails extension cleanup, variable declarations.

diff --git a/rails/shell/functions b/rails/shell/functions
--- a/rails/shell/functions
+++ b/rails/shell/functions
@@ -2,12 +2,13 @@
 
 rails_initialize()
 {
+  typeset -gx log_path shared_path project_root
+
   log_path="${shared_path}/log" # For backup_database
-  export log_path shared_path
 
   if [[ "$action" != "help" ]] && user is root
   then # Sanity check
-    error "Can not work as root with rails extension."
+    log error "Can not work as root with rails extension."
   fi
 
   true ${project_root:="$HOME"}
@@ -38,36 +39,40 @@ CLI Arguments:
 
 ralis_cli()
 {
+  typeset -gx repository_url environment project database server scm_flags > /dev/null 2>&1
+  typeset -ga extension_args > /dev/null 2>&1
+  local number_of_args
+
   number_of_args=${#extension_args[@]}
 
-  for ((index=0 ; index < $number_of_args ; index++))
+  for (( index=0 ; index < $number_of_args ; index++ ))
   do
     token="${extension_args[$index]}"
 
     case "$token" in
-      -r|--repo|--repository)
+      (-r|--repo|--repository)
         repository_url="${extension_args[$((++index))]}"
         ;;
-      -E|--environment|--env)
+      (-E|--environment|--env)
         environment="${extension_args[$((++index))]}"
         ;;
-      -p|--project)
+      (-p|--project)
         project="${extension_args[$((++index))]}"
         ;;
-      -D|--database|--db)
+      (-D|--database|--db)
         database="${extension_args[$((++index))]}"
         ;;
-      -s|--server)
+      (-s|--server)
         server="${extension_args[$((++index))]}"
         ;;
-      --scm-flag|-F)
+      (--scm-flag|-F)
         scm_flags+=("${extension_args[$((++index))]}")
         ;;
-      --help|-h)
+      (--help|-h)
         rails_usage
         exit 0
         ;;
-      --licence)
+      (--licence)
         display_extension_licence
         exit 0
         ;;
@@ -95,10 +100,10 @@ configure_database_yml()
     fi
   fi
 
-  if [[ -n "${database}" ]] && command exists gem
+  if variable is nonempty database && command exists gem
   then
     case "$database" in
-      postgresql)
+      (postgresql)
         install_gems pg
         if [[ "$?" -ne 0 ]] ; then
           pg_config=$(command -v pg_config)
@@ -107,7 +112,7 @@ configure_database_yml()
         fi
         ;;
 
-      mysql)
+      (mysql)
         install_gems mysql
         if [[ "$?" -ne 0 ]] ; then
           mysql_config=$(command -v mysql_config)
@@ -116,15 +121,15 @@ configure_database_yml()
         fi
         ;;
 
-      mongodb)
+      (mongodb)
         install_gems mongomapper
         ;;
 
-      riak)
+      (riak)
         true # This would be cool eh?
         ;;
 
-      sqlite*|*)
+      (sqlite*|*)
         install_gems sqlite3
         ;;
     esac
@@ -134,51 +139,68 @@ configure_database_yml()
 configure_profiles()
 {
   # Ensure the .smrc file and the profiles are setup properly.
-  files exist "$HOME/.bashrc" "$HOME/.bash_profile" || error "No profile files found"
+  files exist "$HOME/.bashrc" "$HOME/.bash_profile" || log error "No profile files found"
 
-  files contain string '\.smrc' in "$HOME/.bashrc" ||
+  if ! files contain string '\.smrc' in "$HOME/.bashrc"
+  then
     files write \
       string '[[ -s "$HOME/.smrc" ]] && . "$HOME/.smrc"' \
       to "$HOME/.bashrc"
+  fi
 
-  files contain string '\.bashrc' in "$HOME/.bash_profile" ||
+  if ! files contain string '\.bashrc' in "$HOME/.bash_profile"
+  then
     files write  \
       string '[[ "-s $HOME/.bashrc" ]] && . "$HOME/.bashrc"' \
       to "$HOME/.bash_profile"
+  fi
 
-  files contain string '\.rvmrc' in "$HOME/.bash_profile" ||
+  if ! files contain string '\.rvmrc' in "$HOME/.bash_profile"
+  then
     files write \
       string '[[ -s "$HOME/current/.rvmrc" ]] && . "$HOME/current/.rvmrc"' \
       to "$HOME/.bash_profile"
+  fi
 }
 
 configure_smrc()
 { # TODO: Separate project specific vs rails specific env vars into project module.
 
-  [[ -n "${project}" ]] || error "project variable is not set, please run 'sm smrc' and edit '~/.smrc'."
+  [[ -n "${project}" ]] || log error "project variable is not set, please run 'sm smrc' and edit '~/.smrc'."
 
   # TODO: These variables should be read & set via the defaults module.
   local _config="${HOME}/.smrc"
 
-  files exists "${_config}" ||
-    error ".smrc file does not exist, run following command to generate it:\n\n sm smrc\n"
+  if ! file exists "${_config}"
+  then
+    sm smrc
+  fi
 
-  files contain string 'project=' in "${_config}" ||
+  if ! file contain string 'project=' in "${_config}"
+  then
     files write \
       string "\nexport project=\"${project:-$user}\"" \
       append to ${_config}
+  fi
 
-  [[ -n "${environment}" ]] || error "environment variable is not set, please run 'sm smrc' and edit '~/.smrc'."
+  if variable is empty environment
+  then
+    log error "environment variable is not set, please run 'sm smrc' and edit '~/.smrc'."
+  fi
 
-  files contain string 'environment=' in "${_config}" ||
+  if ! files contain string 'environment=' in "${_config}"
+  then
     files write \
       string "\nexport environment=\"$environment\"" \
       append to ${_config}
+  fi
 
-  files contain string 'RAILS_ENV=' in "${_config}" ||
+  if ! files contain string 'RAILS_ENV=' in "${_config}"
+  then
     files write \
       string "\nexport RAILS_ENV=\"$environment\"" \
       append to ${_config}
+  fi
 
   if [[ -n "${repository_url}" ]] &&
     ! files contain string "repository_url=" in "${_config}"
@@ -188,8 +210,9 @@ configure_smrc()
       append to "${_config}"
   fi
 
-  if [[ -n "${database}" ]] &&
-    ! files contain string 'database=' in "${_config}"
+
+  if variable is nonempty database &&
+    ! file contain string 'database=' in "${_config}"
   then
     files write \
       string "export database=\"${database}\"" \
@@ -210,9 +233,9 @@ setup_shared_path()
 
 configure_rvm()
 {
-  if [[ ! -s "${HOME}/.rvm/scripts/rvm" ]]
+  if file is empty "${HOME}/.rvm/scripts/rvm"
   then
-    if [[ ! -s "${HOME}/.rvmrc" ]] ||
+    if file is empty "${HOME}/.rvmrc" ||
       ! files contain string 'rvm_path=' in "$HOME/.rvmrc"
     then
       files write \
@@ -237,9 +260,10 @@ configure_rvm()
     rvm_install
   fi
 
-  [[ -f "$HOME/.bash_profile" ]] || touch "$HOME/.bash_profile"
+  if file is missing "$HOME/.bash_profile"
+  then file create "$HOME/.bash_profile" ; fi
 
-  if [[ ! -s "$shared_path/$project/.rvmrc" ]]
+  if file is empty "$shared_path/$project/.rvmrc"
   then
     (
       files source \
@@ -265,26 +289,26 @@ configure_rvm()
 setup_application_server()
 {
   case "${server:-}" in
-    unicorn)
+    (unicorn)
       # TODO: Extension check
       modules unicorn
       unicorn_setup
       ;;
-    mongrel2)
+    (mongrel2)
       NIY "mongrel2 is not implemented yet for the rails extension."
       modules mongrel2
       mongrel2_setup
       ;;
-    thin)
+    (thin)
       modules thin
       setup
       ;;
-    passenger) # Standalone
+    (passenger) # Standalone
       NIY "passenger is not implemented yet for the rails extension."
       modules passenger
       passenger_setup
       ;;
-    *)
+    (*)
       # Default to Unicorn
       modules unicorn
       unicorn_setup
@@ -308,7 +332,7 @@ bootstrap_gems()
 
       bundle ${bundle_args[@]}
     else
-      error "'gem' command not found, not installing bundler."
+      log error "'gem' command not found, not installing bundler."
     fi
   )
 }
@@ -321,7 +345,8 @@ rails_setup()
   log step "Configuring profiles (~/.rvmrc, ~/.bashrc ~/.bash_profile)" \
     configure_profiles
 
-  [[ -n "shared_path" ]] || error "shared_path not set"
+  if variable is empty shared_path
+  then log error "shared_path not set" ; fi
 
   paths create "${shared_path}"
 
@@ -333,8 +358,10 @@ rails_setup()
   log step "Configuring database.yml (~/shared/config/database.yml)" \
     configure_database_yml
 
-  paths exists "$shared_path/$project" ||
+  if ! paths exists "$shared_path/$project"
+  then
     fetch_uri "$repository_url" "$shared_path/$project" ${scm_flags[@]}
+  fi
 
   configure_rvm
 
@@ -351,16 +378,16 @@ rails_server()
 
   if command exists "ruby"
   then
-    if [[ -s "script/${action}" ]]
+    if file is nonempty "script/${action}"
     then
       $ruby script/${action}
 
-    elif [[ -s "script/rails" ]]
+    elif file is nonempty "script/rails"
     then
       $ruby script/rails ${action}
     fi
   else
-    error "A default ruby does not seem to be set, cannot run ${action}"
+    log error "A default ruby does not seem to be set, cannot run ${action}"
   fi
 }
 
@@ -370,10 +397,10 @@ rails_dbconsole()
 
   if command exists "ruby"
   then
-    if [[ -s "script/${action}" ]]
+    if file is nonempty "script/${action}"
     then
       ruby script/${action}
-    elif [[ -s "script/rails" ]]
+    elif file is nonempty "script/rails"
     then
       ruby script/rails ${action}
     elif command exists rails
@@ -383,7 +410,7 @@ rails_dbconsole()
       true # TODO: raw psql/mysql/etc... based on database.yml
     fi
   else
-    error "'ruby' does not exist in the path, cannot run ${action}"
+    log error "'ruby' does not exist in the path, cannot run ${action}"
   fi
 }
 
@@ -393,10 +420,10 @@ rails_console()
 
   if command exists ruby
   then
-    if [[ -s "script/${action}" ]]
+    if file is nonempty "script/${action}"
     then
       ruby script/${action}
-    elif [[ -s "script/rails" ]]
+    elif file is nonempty "script/rails"
     then
       ruby script/rails ${action}
     elif command exists rails
@@ -404,7 +431,7 @@ rails_console()
       rails ${action}
     fi
   else
-    error "'ruby' does not exist in the path, cannot run ${action}"
+    log error "'ruby' does not exist in the path, cannot run ${action}"
   fi
 }
 
@@ -419,7 +446,8 @@ rails_migrate()
 
   if ! command exists rake
   then
-    install_gems rake
+    if !  install_gems rake
+    then log error "There was an error installing rake" ; fi
   fi
 
   rake db:migrate --trace
@@ -429,20 +457,20 @@ rails_new()
 {
   if command exists "ruby"
   then
-    if [[ -s "script/${action}" ]]
+    if file is nonempty "./script/${action}"
     then
-      ruby script/${action}
+      ruby ./script/${action}
 
-    elif [[ -s "script/rails" ]]
+    elif file is nonempty "./script/rails"
     then
-      ruby script/rails ${action}
+      ruby ./script/rails ${action}
 
     elif command exists rails
     then
       rails ${action}
     fi
   else
-    error "'ruby' does not exist in the path, cannot run ${action}"
+    log error "'ruby' does not exist in the path, cannot run ${action}"
   fi
 }
 
@@ -452,10 +480,10 @@ rails_generate()
 
   if command exists "ruby"
   then
-    if [[ -s "script/${action}" ]]
+    if file is nonempty "script/${action}"
     then
       ruby script/${action}
-    elif [[ -s "script/rails" ]]
+    elif file is nonempty "script/rails"
     then
       ruby script/rails ${action}
     elif command exists rails
@@ -463,7 +491,7 @@ rails_generate()
       rails ${action}
     fi
   else
-    error "'ruby' does not exist in the path, cannot run ${action}"
+    log error "'ruby' does not exist in the path, cannot run ${action}"
   fi
 }
 
@@ -472,15 +500,14 @@ rails_bootstrap()
   paths enter "${release_path}"
 
   if [[ -s *.gems ]] && command exists "rvm"
-  then
-    rvm gemset import *.gems
-  fi
+  then rvm gemset import *.gems ; fi
 
-  if [[ -s "Gemfile" ]]
+  if file is nonempty "Gemfile"
   then
     if ! command exists bundle
     then
-      install_gems bundler
+      if ! install_gems bundler
+      then log "Installing bundler gem failed." ; fi
     fi
   elif files contain string "config.gem" in "config/environment.rb"
   then
@@ -491,7 +518,8 @@ rails_bootstrap()
 
   if ! command exists rake
   then
-    install_gems rake 0.8.7
+    if ! install_gems rake 0.9.2
+    then log warn "Installing rake gem failed." ; fi
   fi
 
   if command exists rake
@@ -499,7 +527,7 @@ rails_bootstrap()
     rake db:create
     rake db:migrate
   else
-    warn "'rake' command is missing, skipping db:create and db:migrate tasks."
+    log warn "'rake' command is missing, skipping db:create and db:migrate tasks."
   fi
 }
 
@@ -509,7 +537,8 @@ rails_install()
 
   if ! command exists rails
   then
-    install_gems rails
+    if ! install_gems rails
+    then log warn "Installing rails gem failed" ; fi
   fi
 }
 
@@ -521,13 +550,13 @@ install_gem()
 install_gems() {
   local _gem _gems=("$@") _result=0
 
-  (( ${#_gems[@]} > 0 )) ||
-    fail "Cannot install gems, as no gem names were given!"
+  if (( ${#_gems[@]} < 1 ))
+  then
+    log fail "Cannot install gems, as no gem names were given!"
+  fi
 
   for _gem in "${_gems[@]}"
-  do
-    install_gem ${_gem} || (( _result++ ))
-  done
+  do install_gem ${_gem} || (( _result++ )) ; done
 
   return $_result
 }
@@ -546,7 +575,10 @@ rvm_install()
 
   local _files=( $(files nonempty "${rvm_files[@]}") )
 
-  [[ -z "${_files}" ]]  || files source ${files}
+  if variable is nonempty
+  then
+    files source ${_files}
+  fi
 
   if ! command is function rvm
   then
